language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t antonandrushin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonandrushin/react-test npm test

after_success:
  - docker build -t antonandrushin/multi-nginx ./nginx
  - docker build -t antonandrushin/multi-server ./server
  - docker build -t antonandrushin/multi-worker ./worker
  - docker build -t antonandrushin/multi-client ./client
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push antonandrushin/multi-nginx
  - docker push antonandrushin/multi-server
  - docker push antonandrushin/multi-worker
  - docker push antonandrushin/multi-client

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-687633183315
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY